### ISSUE TITLE
New events are always added at the bottom of the view

### ISSUE THREAD

**Issue by maadani** [exallium/RxRecyclerView#2]
The position of an item in the RxRecyclerViewAdapter is set according to the position in the key list of the internal container.
Since new keys are always added to the end of the key list, new items are always displayed at the bottom of the view.
Suggestion:
I think the RxRecyclerViewAdapter should supply a constructor which gets a Container as a parameter and use it instead of the default container. This way developers can apply their own display order.
Thanks,
E.

**Comment by exallium** [comment]
Hi, thanks for the feedback. I plan to implement 2 new constructors today. One which let's you hand in your own Container implementation, and one which allows you to hand in a comparator object.

The internal container will use this comparator to locate where an item should go using a binary search algorithm.

The Container implementation will be of the methods on the container class within recycler view. You will be able to write your own and hand it in. I will be keeping the internal one in place as well as I have designed it to be as performant as possible.

This should be done later today.

Great idea!

Thanks.

**Comment by maadani** [comment]
Thanks!
I started working on a solution but I didn't get a chance to check it.
Feel free to use it: https://github.com/maadani/RxRecyclerView
Thanks again,
E.

**Comment by exallium** [comment]
I took a look =)

In an effort to keep the library small I plan to just use Java's built in Comparator<T> interface and create an interface based off my Container's public methods (and externalize the container to make it easily extendible).  This should allow people to have as much flexibility with the container as they want (though I believe the Comparator<T> should solve all of the sort based usecases)

**Comment by exallium** [comment]
Hello, This is resolved as of version 1.1.0 =)

**Comment by maadani** [comment]
Looks good.

I implemented my own container and it seems to be working fine.

Thanks a lot,

E.
