### ISSUE TITLE
Existing elements are not always get updated

### ISSUE THREAD

**Issue by maadani** [exallium/RxRecyclerView#7]
Hi Alex,

The Adapter is using the same set (TreeSet) to hold the data and keeping its order which results a logic when looking for elements problem.

Consider the following case:
1. We have an Element which contains 2 int attributes: id, value.
2. We want to display the items according to their values, so we are using the group comparator which compares the values. 
3. After two additions, the tree looks like this: the root element has value = 5 and key = 1 and one right child element with value = 10 and key = 2.
4. Now, we want to update the element with key = 2 to have the value 3 (=> a new event is emitted with element with key = 2 and value = 3).

Expected result:
The right son of the tree should be removed and a new node (with key = 2 and value = 3) should be inserted to be inserted.

Real result:
A new node with key = 2 and value = 3 is added to the tree BUT the old node (the right child) is not removed from the tree.

This happens because the value of the new element directs the new element to a different sub tree so the old element with the same key is never compared with.

Currently, I didn't find any workaround since I can't add/remove items from my adapter class.

I think the way to go here is to hold a one set for the keys and one for the sorted values.

Thanks,

E.

**Comment by exallium** [comment]
Yes, this could be solved using a second set.  I'll look into this as soon as I get the chance.
